-- SmarterJobHunt schema
-- Run with: psql -d smarterjobhunt -f db/schema.sql

CREATE EXTENSION IF NOT EXISTS pg_trgm; -- fast ILIKE / fuzzy title search

-- ---------------------------------------------------------------------------
-- companies: one row per employer the scraping agent tracks
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS companies (
    id             SERIAL PRIMARY KEY,
    name           TEXT NOT NULL UNIQUE,
    website        TEXT,
    funding_stage  TEXT NOT NULL DEFAULT 'unknown'
                   CHECK (funding_stage IN (
                       'seed', 'series_a', 'series_b', 'series_c_plus',
                       'public', 'bootstrapped', 'unknown'
                   )),
    funding_amount TEXT,               -- raw display string, e.g. "$25,000,000"
    funding_date   DATE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- company_type: which curated list a company belongs to. This is the
-- second "company DB" -- Fortune 500 / large public companies -- living
-- alongside the original list of ~500 venture-funded companies, in the
-- same table (one row per company either way, `name` stays globally
-- UNIQUE). Existing rows default to 'funded' so this is backward
-- compatible with the DB as it stands today.
--
-- The scraping agent is the source of truth for this value: whichever
-- list it's currently working through, it should set company_type
-- accordingly on insert/upsert, e.g.:
--   INSERT INTO companies (name, website, funding_stage, company_type)
--   VALUES (%s, %s, 'public', 'fortune500')
--   ON CONFLICT (name) DO UPDATE SET company_type = EXCLUDED.company_type;
-- Fortune 500 companies are almost always 'public' under funding_stage
-- too, but company_type is the field that actually drives the list
-- toggle below -- funding_stage keeps its original meaning otherwise.
--
-- Kept in sync BY HAND with two other places when a database is added:
--   - COMPANY_TYPES in backend/routes/jobs.py
--   - COMPANY_TYPES in frontend/src/lib/companyTypes.js
-- (the saved_searches.company_type CHECK further below additionally
-- allows 'both', since that column also has to represent "no restriction"
-- as a bookmarkable/filterable value, which a company itself can't be.)
ALTER TABLE companies ADD COLUMN IF NOT EXISTS company_type TEXT NOT NULL DEFAULT 'funded'
    CHECK (company_type IN ('funded', 'fortune500'));

CREATE INDEX IF NOT EXISTS idx_companies_company_type ON companies (company_type);

-- ---------------------------------------------------------------------------
-- jobs: one row per posting; this is what the scraping agent will populate
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS jobs (
    id             SERIAL PRIMARY KEY,
    company_id     INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    title          TEXT NOT NULL,
    department     TEXT,
    location       TEXT,
    date_posted    DATE NOT NULL DEFAULT CURRENT_DATE,
    source_url     TEXT,
    raw_text       TEXT,               -- full scraped description, for matching later
    is_active      BOOLEAN NOT NULL DEFAULT true,
    scraped_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_jobs_company_id   ON jobs (company_id);
CREATE INDEX IF NOT EXISTS idx_jobs_date_posted  ON jobs (date_posted DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_title_trgm   ON jobs USING gin (title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_jobs_active       ON jobs (is_active) WHERE is_active;

-- Lets the ingestion agent upsert instead of creating duplicate rows on every
-- scrape run. Jobs without a source_url (shouldn't normally happen) fall
-- outside this index and are always inserted fresh.
CREATE UNIQUE INDEX IF NOT EXISTS idx_jobs_dedup
    ON jobs (company_id, source_url) WHERE source_url IS NOT NULL;

-- ---------------------------------------------------------------------------
-- jobs_staging: landing zone for a scrape run before it's cleaned and
-- promoted into `jobs`. Same shape as jobs, plus a few columns for the
-- cleaning workflow itself. Nothing in here is ever read by the live API --
-- job_matches/user_job_status only ever reference already-promoted rows in
-- `jobs`, so this table can be freely inserted into, rewritten, or cleared
-- per batch without any risk to production data.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS jobs_staging (
    id             SERIAL PRIMARY KEY,
    company_id     INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    title          TEXT NOT NULL,
    department     TEXT,
    location       TEXT,
    date_posted    DATE NOT NULL DEFAULT CURRENT_DATE,
    source_url     TEXT,
    raw_text       TEXT,
    scraped_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- One UUID per scrape run -- generated by the scraping agent, the same
    -- value for every row it inserts in that run. Lets a batch be queried,
    -- cleaned, and promoted (or thrown away) as a unit.
    batch_id       UUID NOT NULL,

    -- 'pending' = not yet decided. The auto-clean pass moves obvious cases
    -- to 'approved'/'rejected' and leaves anything ambiguous as 'pending'
    -- for manual review (see POST /api/admin/staging/clean).
    review_status  TEXT NOT NULL DEFAULT 'pending'
                   CHECK (review_status IN ('pending', 'approved', 'rejected')),
    reject_reason  TEXT,       -- why it was flagged, whether auto or manual
    promoted_at    TIMESTAMPTZ -- set once this row has been pushed into jobs
);

CREATE INDEX IF NOT EXISTS idx_jobs_staging_batch  ON jobs_staging (batch_id);
CREATE INDEX IF NOT EXISTS idx_jobs_staging_status ON jobs_staging (review_status);

-- ---------------------------------------------------------------------------
-- users: job seekers using the app
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id             SERIAL PRIMARY KEY,
    full_name      TEXT NOT NULL
                   CHECK (full_name ~ '^[A-Za-z]+( [A-Za-z]+)*$' AND char_length(full_name) BETWEEN 2 AND 50),
    email          TEXT NOT NULL UNIQUE,
    password_hash  TEXT NOT NULL,
    is_verified    BOOLEAN NOT NULL DEFAULT false,
    resume_text    TEXT,               -- used later to compute match scores
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Safe to re-run: adds the column if this schema.sql is being re-applied
-- against a DB created before email verification existed.
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_verified BOOLEAN NOT NULL DEFAULT false;

-- Holds a requested new email address from the profile page until the user
-- clicks the confirmation link sent to it -- `email` itself only changes at
-- that point (see /api/auth/me PUT and /api/auth/confirm-email/<token> in
-- routes/auth.py). NULL means no change is pending. Deliberately NOT
-- UNIQUE: it's unconfirmed, so two different accounts could transiently
-- have the same address pending -- only `email` needs to stay unique, and
-- that's enforced when the change is confirmed.
ALTER TABLE users ADD COLUMN IF NOT EXISTS pending_email TEXT;

-- Google Sign-In: password_hash becomes optional (accounts created via
-- Google have none), google_id stores the Google account's stable "sub"
-- identifier so a repeat Google login (or a password account later linking
-- Google) can be matched. Safe to re-run against a DB created before this
-- existed.
ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_id TEXT UNIQUE;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_has_auth_method;
ALTER TABLE users ADD CONSTRAINT users_has_auth_method
    CHECK (password_hash IS NOT NULL OR google_id IS NOT NULL);

-- Renamed from `username` to `full_name`: full names allow spaces, aren't
-- unique (people can share a name), and don't fit the old handle-style
-- character set. If this schema.sql is being re-applied against a DB that
-- still has the old `username` column, rename it in place so existing data
-- isn't lost.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'username'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'full_name'
    ) THEN
        ALTER TABLE users RENAME COLUMN username TO full_name;
    END IF;
END $$;

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_username_key;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_username_check;

-- Added nullable — unlike is_verified, there's no sane default for
-- existing rows. If you already have users in prod, backfill full_name
-- first, THEN run:
--   ALTER TABLE users ALTER COLUMN full_name SET NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_full_name_check;
ALTER TABLE users ADD CONSTRAINT users_full_name_check
    CHECK (full_name ~ '^[A-Za-z]+( [A-Za-z]+)*$' AND char_length(full_name) BETWEEN 2 AND 50);

-- Default filters: what a user sees pre-filled on Job Listings after the
-- first-login popup. has_set_default_filters flips to true the first time
-- they save OR skip the popup, so it only ever shows once.
ALTER TABLE users ADD COLUMN IF NOT EXISTS default_job_title TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS default_variants SMALLINT NOT NULL DEFAULT 15;

-- Variants count is no longer user-adjustable -- permanently 15. Backfill
-- any rows written back when the default (and the UI selector) was 10/5.
UPDATE users SET default_variants = 15 WHERE default_variants <> 15;
ALTER TABLE users ADD COLUMN IF NOT EXISTS default_posted_within_days INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS default_funding_filter TEXT NOT NULL DEFAULT 'both'
    CHECK (default_funding_filter IN ('both', 'a', 'b'));
ALTER TABLE users ADD COLUMN IF NOT EXISTS has_set_default_filters BOOLEAN NOT NULL DEFAULT false;

-- Plan tier for the profile page's billing section. 'plan' is the simple
-- free/pro gate the rest of the app reads; it's derived from (and kept in
-- sync with) the Stripe columns below by the billing webhook.
ALTER TABLE users ADD COLUMN IF NOT EXISTS plan TEXT NOT NULL DEFAULT 'free'
    CHECK (plan IN ('free', 'pro'));

-- Stripe subscription billing (weekly/monthly plans). subscription_status
-- mirrors Stripe's own status string (active, trialing, past_due, canceled,
-- unpaid, incomplete, incomplete_expired, paused) — left unconstrained since
-- Stripe can add new values. billing_interval is 'week' or 'month', matching
-- the Stripe Price's recurring.interval for whichever plan the user is on.
ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_customer_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_subscription_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_status TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS billing_interval TEXT
    CHECK (billing_interval IN ('week', 'month'));
ALTER TABLE users ADD COLUMN IF NOT EXISTS current_period_end TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_users_stripe_customer_id ON users (stripe_customer_id)
    WHERE stripe_customer_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- job_matches: per-user match % against a job (computed by the AI agent later;
-- until then this table can simply be left empty and the API defaults to null)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS job_matches (
    id             SERIAL PRIMARY KEY,
    user_id        INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    job_id         INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    match_percent  SMALLINT NOT NULL CHECK (match_percent BETWEEN 0 AND 100),
    computed_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, job_id)
);

-- ---------------------------------------------------------------------------
-- user_job_status: the Applied / Rejected toggle + reason from the dashboard
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_job_status (
    id               SERIAL PRIMARY KEY,
    user_id          INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    job_id           INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    status           TEXT NOT NULL CHECK (status IN ('applied', 'rejected')),
    reason_rejected  TEXT,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, job_id)
);

-- ---------------------------------------------------------------------------
-- saved_searches: the sidebar's "Your saved searches" list
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS saved_searches (
    id                  SERIAL PRIMARY KEY,
    user_id             INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name                TEXT NOT NULL,
    job_title            TEXT,
    variants            SMALLINT NOT NULL DEFAULT 15,
    posted_within_days  INTEGER,
    funding_filter      TEXT NOT NULL DEFAULT 'both'
                        CHECK (funding_filter IN ('both', 'a', 'b')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, name)
);

-- Backfill existing saved searches created while variants was still 5/10/15-selectable.
UPDATE saved_searches SET variants = 15 WHERE variants <> 15;

-- Generalized bookmarking: a saved search can now point at any of the
-- Job Listings page's scoped views, not just a plain title+days search --
-- a drilled-into title variant, a single company's "See them all" list, or
-- an Applied/Rejected tracking view. view_type says which shape applies;
-- job_title/variants/posted_within_days/funding_filter keep their existing
-- meaning for 'search' (and job_title + posted_within_days double up for
-- 'variant', see variant_title below); the other columns stay NULL for
-- whichever shapes don't use them. Safe to re-run against a DB created
-- before this existed.
ALTER TABLE saved_searches ADD COLUMN IF NOT EXISTS view_type TEXT NOT NULL DEFAULT 'search'
    CHECK (view_type IN ('search', 'variant', 'company', 'status'));
-- Mirrors the jobs.company_type filter (Both / Funded Startups / Fortune
-- 500) for the 'search' and 'variant' view types, so re-applying one of
-- those bookmarks restores the exact same Company Database dropdown value
-- it was saved under, not just whatever the sidebar currently has selected.
ALTER TABLE saved_searches ADD COLUMN IF NOT EXISTS company_type TEXT NOT NULL DEFAULT 'both'
    CHECK (company_type IN ('both', 'funded', 'fortune500'));
-- 'variant': which "Also matching" pill was drilled into. job_title above
-- still holds the ORIGINAL search title this variant was found under, so
-- "Return to Full List" after re-applying the bookmark lands back on that
-- search rather than an empty title box.
ALTER TABLE saved_searches ADD COLUMN IF NOT EXISTS variant_title TEXT;
-- 'company': which company's "See them all" list this points at. Cascades
-- with the company row itself -- if a company is ever removed, any
-- bookmarks pointing at it go with it rather than linking nowhere.
ALTER TABLE saved_searches ADD COLUMN IF NOT EXISTS company_id INTEGER
    REFERENCES companies(id) ON DELETE CASCADE;
-- 'status': which Track Applications radio (Applied or Rejected) this
-- points at. "All" isn't bookmarkable since it's just the absence of a
-- status filter -- the same as any other view with tracking off.
ALTER TABLE saved_searches ADD COLUMN IF NOT EXISTS status_filter TEXT
    CHECK (status_filter IN ('applied', 'rejected'));
-- Mirrors the "Remote" sidebar checkbox for the 'search' and 'variant' view
-- types, same reasoning as company_type above -- so re-applying a bookmark
-- restores it exactly as it was checked, rather than leaving it at
-- whatever the checkbox currently happens to be.
ALTER TABLE saved_searches ADD COLUMN IF NOT EXISTS remote_only BOOLEAN NOT NULL DEFAULT false;

-- The original UNIQUE (user_id, name) treated the display NAME as the
-- definition of "already bookmarked" -- but `name` is just a human-readable
-- label built by buildBookmarkName() on the frontend, and was never
-- guaranteed to be distinct per view. Concretely: bookmarking "product
-- manager" under Funded Startups, then bookmarking "product manager" again
-- under Fortune 500, produced the identical name and got rejected as a
-- duplicate even though they're two different views (different
-- company_type). Replace it with a constraint on the fields that actually
-- define a unique view -- the same fields JobListings.jsx's
-- `bookmarkedSearch` finder already uses to decide whether the CURRENT view
-- is already bookmarked -- so the database's definition of "duplicate"
-- matches the app's. COALESCE the nullable columns to sentinel values
-- first: Postgres treats NULL <> NULL in unique indexes, so without this,
-- two truly-identical rows that both happen to have NULL in the same
-- column (e.g. two 'company' bookmarks, which never set job_title) would
-- NOT be caught as duplicates.
ALTER TABLE saved_searches DROP CONSTRAINT IF EXISTS saved_searches_user_id_name_key;
-- Dropped and recreated (rather than IF NOT EXISTS'd) whenever its column
-- list changes -- CREATE INDEX IF NOT EXISTS is a no-op against an index
-- that already exists under this name, even with a different definition,
-- so a rename-free ADD COLUMN like remote_only above would otherwise never
-- actually take effect on a database that already ran an earlier version
-- of this file.
DROP INDEX IF EXISTS uq_saved_searches_view;
CREATE UNIQUE INDEX uq_saved_searches_view ON saved_searches (
    user_id,
    view_type,
    COALESCE(job_title, ''),
    COALESCE(variant_title, ''),
    COALESCE(posted_within_days, -1),
    company_type,
    COALESCE(status_filter, ''),
    COALESCE(company_id, -1),
    remote_only
);

CREATE INDEX IF NOT EXISTS idx_saved_searches_user_id ON saved_searches (user_id);
CREATE INDEX IF NOT EXISTS idx_saved_searches_company_id ON saved_searches (company_id)
    WHERE company_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_user_job_status_user_id ON user_job_status (user_id);
CREATE INDEX IF NOT EXISTS idx_job_matches_user_id ON job_matches (user_id);

-- ---------------------------------------------------------------------------
-- job_title_variants: cache of the closest real job titles already in the
-- `jobs` table for a searched title (via pg_trgm similarity), e.g. searching
-- "PM" surfaces "Product Manager", "Program Manager", etc. Shared across all
-- users -- normalized_title is the lowercased/trimmed lookup key so a repeat
-- search for the same title (any casing/spacing, by anyone) hits the cache
-- instead of re-running the similarity query.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS job_title_variants (
    id                SERIAL PRIMARY KEY,
    job_title         TEXT NOT NULL,        -- as originally searched, for display
    normalized_title  TEXT NOT NULL UNIQUE, -- lower(trim(job_title)), for lookup
    variants          JSONB NOT NULL,       -- ordered array of strings, most relevant first
    generated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- ---------------------------------------------------------------------------
-- contact_messages: submissions from the "Contact us" form on the About Us
-- page (routes/contact.py). Stored regardless of whether the email
-- notification goes out -- this table is the durable record; the email
-- (via email_utils.send_contact_email, same Apps Script webhook as
-- verification/reset) is just a heads-up on top of it.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contact_messages (
    id           SERIAL PRIMARY KEY,
    name         TEXT NOT NULL,
    email        TEXT NOT NULL,
    subject      TEXT NOT NULL CHECK (subject IN (
                     'general', 'bug', 'feedback', 'account', 'business', 'other'
                 )),
    message      TEXT NOT NULL,
    emailed      BOOLEAN NOT NULL DEFAULT false,  -- true once the Apps Script send succeeded
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_contact_messages_created_at ON contact_messages (created_at DESC);